#!/bin/bash
set -e

BRANCH_PATH="/aldm_root/source"
REPO="Atomix-Linux/atomix"

if [[ $# -eq 1 ]]; then
  case "$1" in
    "-c")
      branch=$(cat "$BRANCH_PATH" 2> /dev/null | sed -n 's/^Atomix-Linux\/atomix://; /^stable$\|^unstable$/{p;q};')
      case "$branch" in
        "stable" | "unstable")
          echo "$branch"
          exit 0
          ;;
        *)
          echo >&2 "Warning: Unrecognized currently selected branch name '$branch', updates may not succeed."
          echo "$branch"
          exit 0
          ;;
      esac
      ;;
    "-l")
      echo stable
      echo unstable
      # echo USB
      # echo Network
      exit 0
      ;;
    "stable")
      echo "$REPO:$1" > "$BRANCH_PATH"
      exit 0
      ;;
    "unstable")
      echo "The unstable branch has a high risk of breaking."
      echo "Do NOT use it unless you know what you are doing."
      echo "$REPO:$1" > "$BRANCH_PATH"
      exit 0
      ;;
  esac
fi

echo "Usage: steamos-select-branch <-stable|unstable>" 1>&2
